### ISSUE TITLE
Listen for changes

### ISSUE THREAD

**Issue by manueldidonna** [adrielcafe/PufferDB#1]
I would listen for value changes as I do with android shared preferences. I haven't found a built in solution

**Comment by adrielcafe** [comment]
Hi @manueldidonna , thanks for your suggestion.

I intend to add a listener similar to shared preferences, I'm just waiting for some free time to work on that.

And of course, PRs are very welcome!

**Comment by manueldidonna** [comment]
If you want I could make a PR with a simple listener and a rxjava implementation (I don't have enough experience with kotlin channel/flow). I'm using it and it works. 

SharedPreferences uses weak references for listeners (it stores them in a WeakHashMap). I see that more as an hack than a solution, because we should keep in mind that a listener can stop listen at any moment when there is no reference to it anymore. So, personally, I believe we should avoid a listener with a non-deterministic existence
